import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { Invoice } from '@/types/invoice'
import { format } from 'date-fns'

export function generateInvoicePDF(invoice: Invoice): jsPDF {
  const doc = new jsPDF()
  
  // Apply template styling
  const colors = getTemplateColors(invoice.template)
  
  // Header
  doc.setFillColor(colors.primary.r, colors.primary.g, colors.primary.b)
  doc.rect(0, 0, 210, 40, 'F')
  
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text('INVOICE', 15, 25)
  
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Invoice #${invoice.invoice_number}`, 15, 33)
  
  // Company logo placeholder
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('CR AudioViz AI', 150, 20)
  
  // Reset text color
  doc.setTextColor(0, 0, 0)
  
  // From section
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('FROM:', 15, 55)
  
  doc.setFont('helvetica', 'normal')
  doc.text(invoice.from_name, 15, 62)
  doc.text(invoice.from_email, 15, 67)
  doc.text(invoice.from_address, 15, 72)
  doc.text(`${invoice.from_city}, ${invoice.from_state} ${invoice.from_zip}`, 15, 77)
  doc.text(invoice.from_country, 15, 82)
  
  // To section
  doc.setFont('helvetica', 'bold')
  doc.text('BILL TO:', 120, 55)
  
  doc.setFont('helvetica', 'normal')
  doc.text(invoice.to_name, 120, 62)
  doc.text(invoice.to_email, 120, 67)
  doc.text(invoice.to_address, 120, 72)
  doc.text(`${invoice.to_city}, ${invoice.to_state} ${invoice.to_zip}`, 120, 77)
  doc.text(invoice.to_country, 120, 82)
  
  // Invoice details
  doc.setFont('helvetica', 'bold')
  doc.text('Invoice Date:', 15, 95)
  doc.text('Due Date:', 15, 102)
  doc.text('Status:', 15, 109)
  
  doc.setFont('helvetica', 'normal')
  doc.text(format(new Date(invoice.invoice_date), 'MM/dd/yyyy'), 55, 95)
  doc.text(format(new Date(invoice.due_date), 'MM/dd/yyyy'), 55, 102)
  
  // Status with color
  const statusColor = getStatusColor(invoice.status)
  doc.setTextColor(statusColor.r, statusColor.g, statusColor.b)
  doc.setFont('helvetica', 'bold')
  doc.text(invoice.status.toUpperCase(), 55, 109)
  doc.setTextColor(0, 0, 0)
  
  // Items table
  const tableData = invoice.items.map(item => [
    item.description,
    item.quantity.toString(),
    `$${item.rate.toFixed(2)}`,
    `$${item.amount.toFixed(2)}`
  ])
  
  autoTable(doc, {
    startY: 120,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [colors.primary.r, colors.primary.g, colors.primary.b],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 11
    },
    styles: {
      fontSize: 10,
      cellPadding: 5
    },
    columnStyles: {
      0: { cellWidth: 90 },
      1: { cellWidth: 25, halign: 'center' },
      2: { cellWidth: 35, halign: 'right' },
      3: { cellWidth: 35, halign: 'right' }
    }
  })
  
  // Get the final Y position after the table
  const finalY = (doc as any).lastAutoTable.finalY + 10
  
  // Totals section
  const totalsX = 130
  let currentY = finalY
  
  doc.setFont('helvetica', 'normal')
  doc.text('Subtotal:', totalsX, currentY)
  doc.text(`$${invoice.subtotal.toFixed(2)}`, 180, currentY, { align: 'right' })
  
  currentY += 7
  if (invoice.discount_amount > 0) {
    doc.text('Discount:', totalsX, currentY)
    doc.text(`-$${invoice.discount_amount.toFixed(2)}`, 180, currentY, { align: 'right' })
    currentY += 7
  }
  
  doc.text(`Tax (${invoice.tax_rate}%):`, totalsX, currentY)
  doc.text(`$${invoice.tax_amount.toFixed(2)}`, 180, currentY, { align: 'right' })
  
  currentY += 10
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('TOTAL:', totalsX, currentY)
  doc.text(`$${invoice.total.toFixed(2)}`, 180, currentY, { align: 'right' })
  
  // Notes section
  if (invoice.notes) {
    currentY += 15
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Notes:', 15, currentY)
    
    currentY += 7
    doc.setFont('helvetica', 'normal')
    const splitNotes = doc.splitTextToSize(invoice.notes, 180)
    doc.text(splitNotes, 15, currentY)
    currentY += splitNotes.length * 5
  }
  
  // Terms section
  if (invoice.terms) {
    currentY += 10
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Terms & Conditions:', 15, currentY)
    
    currentY += 7
    doc.setFont('helvetica', 'normal')
    const splitTerms = doc.splitTextToSize(invoice.terms, 180)
    doc.text(splitTerms, 15, currentY)
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by CR AudioViz AI Invoice Generator', 105, pageHeight - 10, { align: 'center' })
  
  return doc
}

function getTemplateColors(template: string) {
  switch (template) {
    case 'modern':
      return { primary: { r: 0, g: 51, b: 102 } } // Navy
    case 'classic':
      return { primary: { r: 51, g: 51, b: 51 } } // Dark gray
    case 'minimalist':
      return { primary: { r: 0, g: 0, b: 0 } } // Black
    default:
      return { primary: { r: 0, g: 51, b: 102 } }
  }
}

function getStatusColor(status: string) {
  switch (status) {
    case 'paid':
      return { r: 34, g: 197, b: 94 } // Green
    case 'sent':
      return { r: 59, g: 130, b: 246 } // Blue
    case 'overdue':
      return { r: 227, g: 25, b: 55 } // Red
    default:
      return { r: 156, g: 163, b: 175 } // Gray
  }
}
